# Generated by Django 4.1.7 on 2023-03-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('access_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('report_types', models.ManyToManyField(to='reports.reporttype')),
                ('units', models.ManyToManyField(to='units.unit')),
            ],
        ),
    ]
