# Generated by Django 5.1.4 on 2025-01-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='user_roles|model|user_role|name')),
                ('access_code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='user_roles|model|user_role|access_code')),
                ('report_types', models.ManyToManyField(to='reports.reporttype', verbose_name='user_roles|model|user_role|report_types')),
                ('units', models.ManyToManyField(to='units.unit', verbose_name='user_roles|model|user_role|units')),
            ],
            options={
                'verbose_name': 'user_roles|model|user_role',
                'verbose_name_plural': 'user_roles|model|user_roles',
            },
        ),
    ]
