# Generated by Django 4.1.7 on 2023-04-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reportroute_options_alter_reporttype_options_and_more'),
        ('units', '0002_department_alter_region_options_alter_unit_options_and_more'),
        ('user_roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'user_roles|model|user_role', 'verbose_name_plural': 'user_roles|model|user_roles'},
        ),
        migrations.AlterField(
            model_name='userrole',
            name='access_code',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='user_roles|model|user_role|access_code'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(max_length=64, verbose_name='user_roles|model|user_role|name'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='report_types',
            field=models.ManyToManyField(to='reports.reporttype', verbose_name='user_roles|model|user_role|report_types'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='units',
            field=models.ManyToManyField(to='units.unit', verbose_name='user_roles|model|user_role|units'),
        ),
    ]
