# Generated by Django 5.1.4 on 2025-06-03 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0002_unit_shift_manager_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientWriteOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('to_write_off_at', models.DateTimeField()),
                ('written_off_at', models.DateTimeField(blank=True, null=True)),
                ('is_notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='write_offs.ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_write_offs', to='units.unit')),
            ],
        ),
    ]
