# Generated by Django 5.1.4 on 2025-01-12 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='units|model|department|id')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='units|model|department|name')),
                ('uuid', models.UUIDField(unique=True, verbose_name='units|model|department|uuid')),
            ],
            options={
                'verbose_name': 'units|model|department',
                'verbose_name_plural': 'units|model|departments',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='units|model|region|name')),
            ],
            options={
                'verbose_name': 'units|model|region',
                'verbose_name_plural': 'units|model|regions',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='units|model|unit|id')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='units|model|unit|name')),
                ('uuid', models.UUIDField(unique=True, verbose_name='units|model|unit|uuid')),
                ('office_manager_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dodo_is_api_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.department', verbose_name='units|model|unit|department')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.region', verbose_name='Units|model|unit|region')),
            ],
            options={
                'verbose_name': 'units|model|unit',
                'verbose_name_plural': 'units|model|units',
            },
        ),
    ]
