# Generated by Django 4.1.7 on 2023-04-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='units|model|department|id')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='units|model|department|name')),
                ('uuid', models.UUIDField(unique=True, verbose_name='units|model|department|uuid')),
            ],
            options={
                'verbose_name': 'units|model|department',
                'verbose_name_plural': 'units|model|departments',
            },
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'units|model|region', 'verbose_name_plural': 'units|model|regions'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'units|model|unit', 'verbose_name_plural': 'units|model|units'},
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='units|model|region|name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='dodo_is_api_account_name',
            field=models.CharField(max_length=64, verbose_name='units|model|unit|dodo_is_api_account_name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='units|model|unit|id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='units|model|unit|name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='office_manager_account_name',
            field=models.CharField(max_length=64, verbose_name='units|model|unit|office_manager_account_name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.region', verbose_name='Units|model|unit|region'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='uuid',
            field=models.UUIDField(unique=True, verbose_name='units|model|unit|uuid'),
        ),
        migrations.AddField(
            model_name='unit',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.department', verbose_name='units|model|unit|department'),
        ),
    ]
