# Generated by Django 5.1.4 on 2025-01-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='shift_manager_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
