# Generated by Django 4.1.7 on 2023-04-08 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_department_alter_region_options_alter_unit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.department', verbose_name='units|model|unit|department'),
        ),
    ]
