# Generated by Django 4.1.7 on 2023-04-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('units', '0003_alter_unit_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='dodo_is_api_account_name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='office_manager_account_name',
        ),
        migrations.AddField(
            model_name='unit',
            name='dodo_is_api_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dodo_is_api_units', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='unit',
            name='office_manager_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_manager_units', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='unit',
            name='shift_manager_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_manager_units', to='accounts.account'),
        ),
    ]
