# Generated by Django 5.1.4 on 2025-01-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_alter_unit_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='dodo_is_api_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='office_manager_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
