# Generated by Django 4.1.7 on 2024-04-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_remove_unit_dodo_is_api_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='dodo_is_api_account',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='office_manager_account',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='shift_manager_account',
        ),
        migrations.AddField(
            model_name='unit',
            name='dodo_is_api_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='office_manager_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
