# Generated by Django 4.1.7 on 2023-04-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_remove_unit_dodo_is_api_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='dodo_is_api_account',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='office_manager_account',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='region',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='shift_manager_account',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
