# Generated by Django 5.1.4 on 2025-01-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('login', models.CharField(max_length=255)),
                ('encrypted_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AccountCookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('encrypted_cookies', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'verbose_name_plural': 'accounts cookies',
            },
        ),
        migrations.CreateModel(
            name='AccountTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_access_token', models.CharField(max_length=255)),
                ('encrypted_refresh_token', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'verbose_name_plural': 'accounts tokens',
            },
        ),
    ]
