# Generated by Django 5.1.4 on 2025-01-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountcookies',
            options={'verbose_name_plural': 'accounts cookies'},
        ),
        migrations.AlterModelOptions(
            name='accounttokens',
            options={'verbose_name_plural': 'accounts tokens'},
        ),
        migrations.AlterField(
            model_name='account',
            name='encrypted_login',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='encrypted_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accountcookies',
            name='encrypted_cookies',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accounttokens',
            name='encrypted_access_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accounttokens',
            name='encrypted_refresh_token',
            field=models.CharField(max_length=255),
        ),
    ]
