# Generated by Django 4.1.7 on 2023-04-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='roles',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(3, 'accounts|model|account|role|shift_manager'), (7, 'accounts|model|account|role|office_manager')], null=True, verbose_name='accounts|model|account|role'),
        ),
        migrations.DeleteModel(
            name='AccountRole',
        ),
    ]
