# Generated by Django 5.1.4 on 2025-01-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcookies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accounttokens',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
