# Generated by Django 5.1.4 on 2025-01-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcookies',
            name='encrypted_cookies',
            field=models.CharField(max_length=65535),
        ),
    ]
