# Generated by Django 4.1.7 on 2023-04-23 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_remove_unit_dodo_is_api_account_and_more'),
        ('accounts', '0002_remove_account_roles_account_role_delete_accountrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeManagerSessionCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.department')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftManagerSessionCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
            ],
        ),
        migrations.AddField(
            model_name='dodoisapicredentials',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='units.department'),
        ),
        migrations.DeleteModel(
            name='DodoISSessionCredentials',
        ),
    ]
