# Generated by Django 5.1.4 on 2025-01-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'reports|model|report_route',
                'verbose_name_plural': 'reports|model|report_routes',
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='reports|model|report_type|name')),
                ('verbose_name', models.CharField(max_length=64, verbose_name='reports|model|report_type|verbose_name')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='reports|model|report_type|priority')),
                ('is_active', models.BooleanField(default=False, verbose_name='Reports|model|report_type|is_active')),
            ],
            options={
                'verbose_name': 'reports|model|report_type',
                'verbose_name_plural': 'reports|model|report_types',
            },
        ),
    ]
