# Generated by Django 4.1.7 on 2023-03-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        ('reports', '0001_initial'),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportroute',
            name='telegram_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramchat'),
        ),
        migrations.AddField(
            model_name='reportroute',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='reportroute',
            unique_together={('report_type', 'unit', 'telegram_chat')},
        ),
    ]
