# Generated by Django 4.1.7 on 2023-03-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('telegram', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportroute',
            unique_together={('report_type', 'unit', 'telegram_chat')},
        ),
    ]
