# Generated by Django 5.1.4 on 2025-01-12 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('telegram', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportroute',
            name='telegram_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramchat', verbose_name='reports|model|report_route|telegram chat'),
        ),
        migrations.AddField(
            model_name='reportroute',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit', verbose_name='Reports|model|report_route|unit'),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttype', verbose_name='reports|model|report_type|parent'),
        ),
        migrations.AddField(
            model_name='reportroute',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttype', verbose_name='Reports|model|report_route|report_type'),
        ),
        migrations.AlterUniqueTogether(
            name='reportroute',
            unique_together={('report_type', 'unit', 'telegram_chat')},
        ),
    ]
