# Generated by Django 4.1.7 on 2023-04-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegramchat_created_at_alter_telegramchat_role'),
        ('units', '0002_department_alter_region_options_alter_unit_options_and_more'),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportroute',
            options={'verbose_name': 'reports|model|report_route', 'verbose_name_plural': 'reports|model|report_routes'},
        ),
        migrations.AlterModelOptions(
            name='reporttype',
            options={'verbose_name': 'reports|model|report_type', 'verbose_name_plural': 'reports|model|report_types'},
        ),
        migrations.AlterField(
            model_name='reportroute',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttype', verbose_name='Reports|model|report_route|report_type'),
        ),
        migrations.AlterField(
            model_name='reportroute',
            name='telegram_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramchat', verbose_name='reports|model|report_route|telegram chat'),
        ),
        migrations.AlterField(
            model_name='reportroute',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit', verbose_name='Reports|model|report_route|unit'),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Reports|model|report_type|is_active'),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='reports|model|report_type|name'),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttype', verbose_name='reports|model|report_type|parent'),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='verbose_name',
            field=models.CharField(max_length=64, verbose_name='reports|model|report_type|verbose_name'),
        ),
    ]
