# Generated by Django 4.1.7 on 2023-04-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reportroute_options_alter_reporttype_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporttype',
            old_name='name',
            new_name='alias',
        ),
    ]
