# Generated by Django 5.2.7 on 2025-12-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_inventorystocks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryStocks',
        ),
    ]
