# Generated by Django 4.1.7 on 2023-04-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_name_reporttype_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporttype',
            old_name='verbose_name',
            new_name='name',
        ),
    ]
