# Generated by Django 4.1.7 on 2024-04-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reporttype_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporttype',
            old_name='name',
            new_name='verbose_name',
        ),
    ]
