# Generated by Django 4.1.7 on 2023-03-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(max_length=64)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Private'), (2, 'Group')])),
            ],
        ),
    ]
