# Generated by Django 4.1.7 on 2023-03-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(max_length=64)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Private'), (2, 'Group')])),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_roles.userrole')),
            ],
        ),
    ]
