# Generated by Django 5.2.1 on 2025-10-29 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat ID')),
                ('chat_message_ids', models.JSONField(blank=True, help_text='Id of message in chat, returned by Telegram API', null=True, verbose_name='Chat message IDs')),
                ('text', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Message text')),
                ('media_file_ids', models.JSONField(blank=True, null=True, verbose_name='Media file IDs')),
                ('error_message', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Error message')),
                ('retries_count', models.PositiveIntegerField(default=5, verbose_name='Retries left')),
                ('to_be_sent_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The time at which the message was sent.', verbose_name='To be sent at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('reply_markup', models.JSONField(blank=True, null=True, verbose_name='Reply markup')),
            ],
            options={
                'verbose_name': 'Telegram message',
                'verbose_name_plural': 'Telegram messages',
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('text__isnull', False), ('media_file_ids__isnull', False), _connector='OR'), name='text_or_media_file_ids_not_null', violation_error_message='Either text or media file IDs must be set.'), models.CheckConstraint(condition=models.Q(('media_file_ids__isnull', True), ('reply_markup__isnull', True), _connector='OR'), name='media_file_ids_and_reply_markup_not_both_set', violation_error_message='Reply markup can be set only for text messages.')],
            },
        ),
    ]
