# Generated by Django 5.2.7 on 2025-11-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegrammessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='priority',
            field=models.PositiveSmallIntegerField(default=100, help_text='Lower priority number messages are sent first.', verbose_name='Priority'),
        ),
    ]
